#pragma once
#include "../Library.h"

#ifdef __cplusplus
	#include <zenkit/addon/daedalus.hh>
using ZkParticleEffectInstance = zenkit::IParticleEffect;
#else
typedef struct ZkInternal_ParticleEffectInstance ZkParticleEffectInstance;
#endif

ZKC_API float ZkParticleEffectInstance_getPpsValue(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsValue(ZkParticleEffectInstance* slf, float ppsValue);
ZKC_API ZkString ZkParticleEffectInstance_getPpsScaleKeysS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsScaleKeysS(ZkParticleEffectInstance* slf, ZkString ppsScaleKeysS);
ZKC_API int32_t ZkParticleEffectInstance_getPpsIsLooping(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsIsLooping(ZkParticleEffectInstance* slf, int32_t ppsIsLooping);
ZKC_API int32_t ZkParticleEffectInstance_getPpsIsSmooth(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsIsSmooth(ZkParticleEffectInstance* slf, int32_t ppsIsSmooth);
ZKC_API float ZkParticleEffectInstance_getPpsFps(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsFps(ZkParticleEffectInstance* slf, float ppsFps);
ZKC_API ZkString ZkParticleEffectInstance_getPpsCreateEmS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsCreateEmS(ZkParticleEffectInstance* slf, ZkString ppsCreateEmS);
ZKC_API float ZkParticleEffectInstance_getPpsCreateEmDelay(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setPpsCreateEmDelay(ZkParticleEffectInstance* slf, float ppsCreateEmDelay);
ZKC_API ZkString ZkParticleEffectInstance_getShpTypeS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpTypeS(ZkParticleEffectInstance* slf, ZkString shpTypeS);
ZKC_API ZkString ZkParticleEffectInstance_getShpForS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpForS(ZkParticleEffectInstance* slf, ZkString shpForS);
ZKC_API ZkString ZkParticleEffectInstance_getShpOffsetVecS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpOffsetVecS(ZkParticleEffectInstance* slf, ZkString shpOffsetVecS);
ZKC_API ZkString ZkParticleEffectInstance_getShpDistribTypeS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpDistribTypeS(ZkParticleEffectInstance* slf, ZkString shpDistribTypeS);
ZKC_API float ZkParticleEffectInstance_getShpDistribWalkSpeed(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpDistribWalkSpeed(ZkParticleEffectInstance* slf, float shpDistribWalkSpeed);
ZKC_API int32_t ZkParticleEffectInstance_getShpIsVolume(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpIsVolume(ZkParticleEffectInstance* slf, int32_t shpIsVolume);
ZKC_API ZkString ZkParticleEffectInstance_getShpDimS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpDimS(ZkParticleEffectInstance* slf, ZkString shpDimS);
ZKC_API ZkString ZkParticleEffectInstance_getShpMeshS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpMeshS(ZkParticleEffectInstance* slf, ZkString shpMeshS);
ZKC_API int32_t ZkParticleEffectInstance_getShpMeshRenderB(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpMeshRenderB(ZkParticleEffectInstance* slf, int32_t shpMeshRenderB);
ZKC_API ZkString ZkParticleEffectInstance_getShpScaleKeysS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpScaleKeysS(ZkParticleEffectInstance* slf, ZkString shpScaleKeysS);
ZKC_API int32_t ZkParticleEffectInstance_getShpScaleIsLooping(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpScaleIsLooping(ZkParticleEffectInstance* slf, int32_t shpScaleIsLooping);
ZKC_API int32_t ZkParticleEffectInstance_getShpScaleIsSmooth(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpScaleIsSmooth(ZkParticleEffectInstance* slf, int32_t shpScaleIsSmooth);
ZKC_API float ZkParticleEffectInstance_getShpScaleFps(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setShpScaleFps(ZkParticleEffectInstance* slf, float shpScaleFps);
ZKC_API ZkString ZkParticleEffectInstance_getDirModeS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirModeS(ZkParticleEffectInstance* slf, ZkString dirModeS);
ZKC_API ZkString ZkParticleEffectInstance_getDirForS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirForS(ZkParticleEffectInstance* slf, ZkString dirForS);
ZKC_API ZkString ZkParticleEffectInstance_getDirModeTargetForS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirModeTargetForS(ZkParticleEffectInstance* slf, ZkString dirModeTargetForS);
ZKC_API ZkString ZkParticleEffectInstance_getDirModeTargetPosS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirModeTargetPosS(ZkParticleEffectInstance* slf, ZkString dirModeTargetPosS);
ZKC_API float ZkParticleEffectInstance_getDirAngleHead(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirAngleHead(ZkParticleEffectInstance* slf, float dirAngleHead);
ZKC_API float ZkParticleEffectInstance_getDirAngleHeadVar(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirAngleHeadVar(ZkParticleEffectInstance* slf, float dirAngleHeadVar);
ZKC_API float ZkParticleEffectInstance_getDirAngleElev(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirAngleElev(ZkParticleEffectInstance* slf, float dirAngleElev);
ZKC_API float ZkParticleEffectInstance_getDirAngleElevVar(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setDirAngleElevVar(ZkParticleEffectInstance* slf, float dirAngleElevVar);
ZKC_API float ZkParticleEffectInstance_getVelAvg(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVelAvg(ZkParticleEffectInstance* slf, float velAvg);
ZKC_API float ZkParticleEffectInstance_getVelVar(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVelVar(ZkParticleEffectInstance* slf, float velVar);
ZKC_API float ZkParticleEffectInstance_getLspPartAvg(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setLspPartAvg(ZkParticleEffectInstance* slf, float lspPartAvg);
ZKC_API float ZkParticleEffectInstance_getLspPartVar(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setLspPartVar(ZkParticleEffectInstance* slf, float lspPartVar);
ZKC_API ZkString ZkParticleEffectInstance_getFlyGravityS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setFlyGravityS(ZkParticleEffectInstance* slf, ZkString flyGravityS);
ZKC_API int32_t ZkParticleEffectInstance_getFlyColldetB(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setFlyColldetB(ZkParticleEffectInstance* slf, int32_t flyColldetB);
ZKC_API ZkString ZkParticleEffectInstance_getVisNameS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisNameS(ZkParticleEffectInstance* slf, ZkString visNameS);
ZKC_API ZkString ZkParticleEffectInstance_getVisOrientationS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisOrientationS(ZkParticleEffectInstance* slf, ZkString visOrientationS);
ZKC_API int32_t ZkParticleEffectInstance_getVisTexIsQuadpoly(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisTexIsQuadpoly(ZkParticleEffectInstance* slf, int32_t visTexIsQuadpoly);
ZKC_API float ZkParticleEffectInstance_getVisTexAniFps(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisTexAniFps(ZkParticleEffectInstance* slf, float visTexAniFps);
ZKC_API int32_t ZkParticleEffectInstance_getVisTexAniIsLooping(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisTexAniIsLooping(ZkParticleEffectInstance* slf, int32_t visTexAniIsLooping);
ZKC_API ZkString ZkParticleEffectInstance_getVisTexColorStartS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisTexColorStartS(ZkParticleEffectInstance* slf, ZkString visTexColorStartS);
ZKC_API ZkString ZkParticleEffectInstance_getVisTexColorEndS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisTexColorEndS(ZkParticleEffectInstance* slf, ZkString visTexColorEndS);
ZKC_API ZkString ZkParticleEffectInstance_getVisSizeStartS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisSizeStartS(ZkParticleEffectInstance* slf, ZkString visSizeStartS);
ZKC_API float ZkParticleEffectInstance_getVisSizeEndScale(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisSizeEndScale(ZkParticleEffectInstance* slf, float visSizeEndScale);
ZKC_API ZkString ZkParticleEffectInstance_getVisAlphaFuncS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisAlphaFuncS(ZkParticleEffectInstance* slf, ZkString visAlphaFuncS);
ZKC_API float ZkParticleEffectInstance_getVisAlphaStart(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisAlphaStart(ZkParticleEffectInstance* slf, float visAlphaStart);
ZKC_API float ZkParticleEffectInstance_getVisAlphaEnd(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setVisAlphaEnd(ZkParticleEffectInstance* slf, float visAlphaEnd);
ZKC_API float ZkParticleEffectInstance_getTrlFadeSpeed(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setTrlFadeSpeed(ZkParticleEffectInstance* slf, float trlFadeSpeed);
ZKC_API ZkString ZkParticleEffectInstance_getTrlTextureS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setTrlTextureS(ZkParticleEffectInstance* slf, ZkString trlTextureS);
ZKC_API float ZkParticleEffectInstance_getTrlWidth(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setTrlWidth(ZkParticleEffectInstance* slf, float trlWidth);
ZKC_API float ZkParticleEffectInstance_getMrkFadesPeed(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setMrkFadesPeed(ZkParticleEffectInstance* slf, float mrkFadesPeed);
ZKC_API ZkString ZkParticleEffectInstance_getMrktExtureS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setMrktExtureS(ZkParticleEffectInstance* slf, ZkString mrktExtureS);
ZKC_API float ZkParticleEffectInstance_getMrkSize(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setMrkSize(ZkParticleEffectInstance* slf, float mrkSize);
ZKC_API ZkString ZkParticleEffectInstance_getFlockMode(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setFlockMode(ZkParticleEffectInstance* slf, ZkString flockMode);
ZKC_API float ZkParticleEffectInstance_getFlockStrength(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setFlockStrength(ZkParticleEffectInstance* slf, float flockStrength);
ZKC_API int32_t ZkParticleEffectInstance_getUseEmittersFor(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setUseEmittersFor(ZkParticleEffectInstance* slf, int32_t useEmittersFor);
ZKC_API ZkString ZkParticleEffectInstance_getTimeStartEndS(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setTimeStartEndS(ZkParticleEffectInstance* slf, ZkString timeStartEndS);
ZKC_API int32_t ZkParticleEffectInstance_getMBiasAmbientPfx(ZkParticleEffectInstance const* slf);
ZKC_API void ZkParticleEffectInstance_setMBiasAmbientPfx(ZkParticleEffectInstance* slf, int32_t mBiasAmbientPfx);
